url: 
#baseurl: 

# Site Settings
title: Sammy Poudel
author: Sammy Poudel
description: "My Personal Webiste"
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
